config/routes.rb
Rails.application.routes.draw do
  get 'persons/search', to: 'persons#search'
  post 'people/create', to: 'persons#create', as: 'people'
  get 'persons/:id/calendar', to: 'persons#calendar', as: 'person_calendar'
  get 'persons/:id/calendar/new_date', to: 'persons#new_date', as: 'person_new_date'
  get 'persons/:id/calendar/edit', to: 'persons#calendar_edit', as: 'person_calendar_edit'
  get 'medics/:id/calendar', to: 'medics#calendar', as: 'medic_calendar'
  get 'medics/:id/next_dates', to: 'medics#next_dates', as: 'medic_next_dates'
  get 'kinesiologists/:id/calendar', to: 'kinesiologists#calendar', as: 'kinesiologist_calendar'
  get 'person_dates/create_medics_dates', to: 'person_dates#create_medics_dates'
  get 'person_dates/create_kine_dates', to: 'person_dates#create_kinesiologist_dates'
  get 'persons/:id/calendar/available_dates', to: 'person_dates#available_dates', as: 'available_dates'
  get 'create_attention_capacity', to: 'application#create_attention_capacity'
  get 'create_patients', to: 'application#create_patients'
  get 'month_avalaible_dates', to: 'application#month_avalaible_dates'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'run_heuristic', to: 'application#run_heuristic'
  get 'person_dates/:id/untake', to: 'person_dates#untake', as:'untake_person_date'
  get 'persons/:id/untake_bucket/:bucket_id', to: 'persons#untake_bucket', as:'untake_bucket'
  get 'get_file', to: 'application#show_error_charging_date'
  get 'medics/:id/next_date_for_patients', to: 'person_dates#next_date_for_patients'
  get 'dump_db', to: 'application#dump_db'
  get '262', to: 'application#generate_262'
  get 'load_windwos_from_file', to: 'application#load_windwos_from_file'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'file_heuristic', to: 'application#get_result_of_heuristic'

  resources :persons, :medics, :kinesiologists ,:person_dates
  root 'application#index'
end

app/models/medic.rb
class Medic < ApplicationRecord
  serialize :attention, JSON
  has_many :buckets, dependent: :destroy

  def available_dates person, date = Date.tomorrow
    return PersonDate.where(medic_id: id, person_id: 1, date: date).all if Bucket.available_for?(person, id, date)
    []
  end

  def month_available_dates date = Date.tomorrow
    available = []
    Array(date..date.end_of_month + 3.month).each do |d|
      available << d if Bucket.where(medic_id: id, date: d).where("capacity > 0").count > 0
    end
    available
  end

  def patients_for_today
    dates = []
    PersonDate.where(medic_id: id, date: Date.current).where.not(person_id: 1).sort_by { |d| d.time.to_time }.each do |pd|
      next_date = pd.next_dates.first
      dates << [pd, next_date]
      if !pd.next_dates.second.blank? and next_date.date == pd.next_dates.second.date
        dates << [pd, pd.next_dates.second]
      end
    end
    dates
  end

  def next_dates_for_my_patients date = Date.current
    dates = []
    PersonDate.where(medic_id: id, date: date).where.not(person_id: 1).each do |pd|
      unless pd.next_date(date + 1.day).blank?
        dates << pd.next_date(date + 1.day)
      end
    end
    dates.uniq.sort_by { |d| [d.date, d.time.to_time] }
  end

  def create_dates date = Date.current
    week = date.at_beginning_of_week
    attention.each do |attention|
      attention[1].each do |d|
        d = d.to_i
        day = week + d.day
        b = Bucket.where(medic_id: self.id, date: day).first_or_create!
        time = attention[0]
        pd = PersonDate.where(date: day, time: time, medic_id: self.id).first_or_create! do |personal|
          personal.person_id = 1
          b.update_attribute :capacity, b.capacity + 1
        end
      end
    end
  end

  def to_csv
    [self.id, self.name, self.type.blank? ? 'Atencion Primaria' : 'Kinesiologia']
  end
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  def calendar
    @medic_id = params[:id]
    @type = 'agendaDay'

    render 'layouts/calendar'
  end
  def create
    @medic = Medic.new(permit_params)
    @medic.save
    redirect_to @medic
  end

  def edit
    @medic = Medic.find(params[:id])
  end

  def index
    @medics = Medic.where(type: nil)
  end

  def new
    @medic = Medic.new
  end

  def show
    @medic = Medic.find(params[:id])
  end

  def update
    @medic = Medic.find(params[:id])
    if @medic.update(permit_params)
      redirect_to @medic
    else
      render 'edit'
    end
  end

  def next_dates
    medic = Medic.find(params[:id])
    @dates = medic.patients_for_today
    render 'person_dates/index',layout: false
  end

  private
  def permit_params
    params.require(:medic).permit(:name, :rut, :phone, :color, attention: {})
  end
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/views/medics/_form.html.erb
<%= form_with model: @medic, local: true do |form| %>

  <% if @medic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@medic.errors.count, "error") %> Prohibido
        Guardar este medico
      </h2>
      <ul>
        <% @medic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :rut %><br>
    <%= form.text_field :rut %>
  </p>

  <p>
    <%= form.label :telefono %><br>
    <%= form.text_field :phone %>
  </p>

  <p>
    <%= form.label :color %>
    <%= form.text_field :color %>
  </p>

  <div class="table-responsive">
    <table class="table table-hover">
      <tr>
        <th>Hora</th>
        <th>Lunes</th>
        <th>Martes</th>
        <th>Miercoles</th>
        <th>Jueves</th>
        <th>Viernes</th>
      </tr>
      <% ['8', '9', '10', '11', '12', '13', '14', '15', '16', '17'].each do |h| %>
        <% ['00', '15', '30', '45'].each do |m| %>
          <tr>
            <td><%= h + ':' + m %></td>
            <% 5.times do |i| %>
              <td><%= form.check_box "attention[" + h + ':' + m + "]", {multiple: true, checked: (@medic.attention[h + ':' + m].include? i.to_s unless @medic.attention.blank? or @medic.attention[h + ':' + m].blank?)}, i, false %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>

    </table>

  </div>
  <p>
    <%= form.submit :enviar %>
  </p>

<% end %>

app/views/medics/edit.html.erb
<h1>Editar Medico <%= @medic.name %></h1>

<%= render 'form' %>

<%= link_to 'Atras', medics_path %>

app/views/medics/index.html.erb
<h1>Listado de Medicos Atencion Primaria</h1>
<div class="table-responsive">

<table class="table table-hover">
  <tr>
    <th>Nombre</th>
    <th>Rut</th>
    <th>Telefono</th>
    <th>Agenda</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @medics.each do |medic| %>
    <tr>
      <td><%= medic.name %></td>
      <td><%= medic.rut %></td>
      <td><%= medic.phone %></td>
      <td><%= link_to 'Ver agenda', medic_calendar_path(medic), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Siguientes citas', medic_next_dates_path(medic) , class: 'btn btn-primary'%></td>
      <td><%= link_to 'Ver', medic_path(medic), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Editar', edit_medic_path(medic), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>
  </div>

app/views/medics/new.html.erb
<h1>Nuevo Medico </h1>

<%= render 'form' %>

<%= link_to 'Atras', medics_path %>

app/views/medics/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @medic.name %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @medic.rut %>
</p>
<p>
  <strong>Telefono:</strong>
  <%= @medic.phone %>
</p>

<%= link_to 'Editar', edit_medic_path(@medic) %>
<%= link_to 'Volver', medics_path %>