config/routes.rb
Rails.application.routes.draw do
  get 'persons/search', to: 'persons#search'
  post 'people/create', to: 'persons#create', as: 'people'
  get 'persons/:id/calendar', to: 'persons#calendar', as: 'person_calendar'
  get 'persons/:id/calendar/new_date', to: 'persons#new_date', as: 'person_new_date'
  get 'persons/:id/calendar/edit', to: 'persons#calendar_edit', as: 'person_calendar_edit'
  get 'medics/:id/calendar', to: 'medics#calendar', as: 'medic_calendar'
  get 'medics/:id/next_dates', to: 'medics#next_dates', as: 'medic_next_dates'
  get 'kinesiologists/:id/calendar', to: 'kinesiologists#calendar', as: 'kinesiologist_calendar'
  get 'person_dates/create_medics_dates', to: 'person_dates#create_medics_dates'
  get 'person_dates/create_kine_dates', to: 'person_dates#create_kinesiologist_dates'
  get 'persons/:id/calendar/available_dates', to: 'person_dates#available_dates', as: 'available_dates'
  get 'create_attention_capacity', to: 'application#create_attention_capacity'
  get 'create_patients', to: 'application#create_patients'
  get 'month_avalaible_dates', to: 'application#month_avalaible_dates'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'run_heuristic', to: 'application#run_heuristic'
  get 'person_dates/:id/untake', to: 'person_dates#untake', as:'untake_person_date'
  get 'persons/:id/untake_bucket/:bucket_id', to: 'persons#untake_bucket', as:'untake_bucket'
  get 'get_file', to: 'application#show_error_charging_date'
  get 'medics/:id/next_date_for_patients', to: 'person_dates#next_date_for_patients'
  get 'dump_db', to: 'application#dump_db'
  get '262', to: 'application#generate_262'
  get 'load_windwos_from_file', to: 'application#load_windwos_from_file'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'file_heuristic', to: 'application#get_result_of_heuristic'

  resources :persons, :medics, :kinesiologists ,:person_dates
  root 'application#index'
end

app/models/kinesiologist.rb
class Kinesiologist < Medic
  serialize :attention, JSON
end

app/controllers/kinesiologists_controller.rb
class KinesiologistsController < ApplicationController
  def calendar
    @medic_id = params[:id]
    @type = 'agendaDay'

    render 'layouts/calendar'
  end

  def create
    @kine = Kinesiologist.new(permit_params)
    @kine.save!
    redirect_to @kine
  end

  def edit
    @kine = Kinesiologist.find(params[:id])
  end

  def index
    @kinesiologists = Kinesiologist.all
  end

  def new
    @kine = Kinesiologist.new
  end

  def show
    @kine = Kinesiologist.find(params[:id])
  end

  def update
    @kine = Kinesiologist.find(params[:id])
    if @kine.update(permit_params)
      redirect_to @kine
    else
      render 'edit'
    end
  end

  private
  def permit_params
    params.require(:kinesiologist).permit(:name, :rut, :phone, :color, attention: {})
  end
end

app/helpers/kinesiologists_helper.rb
module KinesiologistsHelper
end

app/views/kinesiologists/_form.html.erb
<%= form_with model: @kine, local: true do |form| %>

  <% if @kine.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@kine.errors.count, "error") %> Prohibido
        Guardar este kinesiologo
      </h2>
      <ul>
        <% @kine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :rut %><br>
    <%= form.text_field :rut %>
  </p>

  <p>
    <%= form.label :telefono %><br>
    <%= form.text_field :phone %>
  </p>
  <p>
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </p>

  <div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>Hora</th>
      <th>Lunes</th>
      <th>Martes</th>
      <th>Miercoles</th>
      <th>Jueves</th>
      <th>Viernes</th>
    </tr>
    <% ['8','9','10','11','12','13','14','15','16','17'].each do |h| %>
      <% ['00','15','30','45'].each do |m| %>
    <tr>
      <td><%= h+':'+m %></td>
      <% 5.times do |i| %>
        <td><%= form.check_box "attention["+h+':'+m+"]", {multiple: true, checked: (@kine.attention[h+':'+m].include? i.to_s unless @kine.attention.blank? or @kine.attention[h+':'+m].blank?)}, i, false %></td>
      <% end %>
    </tr>
    <% end %>
      <% end %>

  </table>

    </div>

  <p>
    <%= form.submit :Enviar%>
  </p>

<% end %>

app/views/kinesiologists/edit.html.erb
<h1>Editar Kinesiologo <%= @kine.name %></h1>

<%= render 'form' %>

<%= link_to 'Atras', kinesiologists_path %>

app/views/kinesiologists/index.html.erb
<h1>Listado de Kinesiologos</h1>

<table class="table table-hover">
  <tr>
    <th>Nombre</th>
    <th>Rut</th>
    <th>Telefono</th>
    <th>Agenda</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @kinesiologists.each do |kine| %>
    <tr>
      <td><%= kine.name %></td>
      <td><%= kine.rut %></td>
      <td><%= kine.phone %></td>
      <td><%= link_to 'Ver Agenda', kinesiologist_calendar_path(kine),class: 'btn btn-primary' %></td>
      <td><%= link_to 'Siguientes citas', medic_next_dates_path(kine) , class: 'btn btn-primary'%></td>
      <td><%= link_to 'Ver', kinesiologist_path(kine), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Editar', edit_kinesiologist_path(kine), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>

app/views/kinesiologists/new.html.erb
<h1>Nuevo Kinesiologo</h1>

<%= render 'form' %>

<%= link_to 'Atras', kinesiologists_path %>

app/views/kinesiologists/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @kine.name %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @kine.rut %>
</p>
<p>
  <strong>Telefono:</strong>
  <%= @kine.phone %>
</p>

<%= link_to 'Editar', edit_kinesiologist_path(@kine) %>
<%= link_to 'Volver', kinesiologists_path %>