config/routes.rb
Rails.application.routes.draw do
  get 'persons/search', to: 'persons#search'
  post 'people/create', to: 'persons#create', as: 'people'
  get 'persons/:id/calendar', to: 'persons#calendar', as: 'person_calendar'
  get 'persons/:id/calendar/new_date', to: 'persons#new_date', as: 'person_new_date'
  get 'persons/:id/calendar/edit', to: 'persons#calendar_edit', as: 'person_calendar_edit'
  get 'medics/:id/calendar', to: 'medics#calendar', as: 'medic_calendar'
  get 'medics/:id/next_dates', to: 'medics#next_dates', as: 'medic_next_dates'
  get 'kinesiologists/:id/calendar', to: 'kinesiologists#calendar', as: 'kinesiologist_calendar'
  get 'person_dates/create_medics_dates', to: 'person_dates#create_medics_dates'
  get 'person_dates/create_kine_dates', to: 'person_dates#create_kinesiologist_dates'
  get 'persons/:id/calendar/available_dates', to: 'person_dates#available_dates', as: 'available_dates'
  get 'create_attention_capacity', to: 'application#create_attention_capacity'
  get 'create_patients', to: 'application#create_patients'
  get 'month_avalaible_dates', to: 'application#month_avalaible_dates'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'run_heuristic', to: 'application#run_heuristic'
  get 'person_dates/:id/untake', to: 'person_dates#untake', as:'untake_person_date'
  get 'persons/:id/untake_bucket/:bucket_id', to: 'persons#untake_bucket', as:'untake_bucket'
  get 'get_file', to: 'application#show_error_charging_date'
  get 'medics/:id/next_date_for_patients', to: 'person_dates#next_date_for_patients'
  get 'dump_db', to: 'application#dump_db'
  get '262', to: 'application#generate_262'
  get 'load_windwos_from_file', to: 'application#load_windwos_from_file'
  get 'load_calendar_from_file', to: 'application#load_calendar_from_file'
  get 'file_heuristic', to: 'application#get_result_of_heuristic'

  resources :persons, :medics, :kinesiologists ,:person_dates
  root 'application#index'
end

app/models/person_date.rb
class PersonDate < ApplicationRecord
  belongs_to :person
  belongs_to :medic

  def start_time
    ntime = time.split(':')
    DateTime.now.change(year: date.year,
                        month: date.month,
                        day: date.day,
                        hour: ntime[0].to_i,
                        min: ntime[1].to_i)
  end

  def self.next_date_of_person id
    PersonDate.where(person_id: id).where("date>=?",Date.tomorrow).order(date: :asc).first
  end

  def next_date date=Date.tomorrow
    PersonDate.where(person_id: person_id).where("date>=?",date).order(date: :asc).first
  end

  def next_dates date=Date.tomorrow
    PersonDate.where(person_id: person_id).where("date>=?",date).order(date: :asc).take(2)
  end

  def is_next?
    self == self.next_date
  end

  def take person_id
    b = Bucket.where(medic_id: medic_id, date: date).first
    b.take person_id
    update_attribute(:person_id, person_id)
  end

  def self.take params
    pd = self.where(medic_id: params[:medic_id], date: params[:date], time: params[:time], person_id: 1).first
    pd.take params[:person_id] if pd
  end

  def untake
    b = Bucket.where(medic_id: medic_id, date: date).first
    if b
      if PersonDate.where(medic_id: medic_id, date: date, person_id: person_id).count == 1
        b.untake person_id
      end
    end
    update_attribute :person_id, 1
  end

  def taked?
    return true unless person.id == 1
    false
  end

  def to_csv
    [self.medic_id, Person.find(person_id).bp, self.date.strftime("%F"), self.time]
  end

  def color
    medic.color
  end
end

app/controllers/person_dates_controller.rb
class PersonDatesController < ApplicationController
  def create
    @date = PersonDate.take(permit_params)
    redirect_to action: :index
  end

  def index
    @medics = Medic.all
    respond_to do |format|
      format.json {
        if params[:medic_id].blank?
          render json: PersonDate.where(date: params[:from].to_date..params[:to].to_date).map { |person_date|
            {title: person_date.person_id != 1 ? person_date.person.bp.to_s + ' con ' + person_date.medic.name : 'Disponible con ' + person_date.medic.name,
             start: person_date.start_time,
             color: person_date.color,
             resourceId: person_date.medic.id,
             taked: person_date.taked?
            }
          }
        else
          render json: PersonDate.where(date: params[:from].to_date..params[:to].to_date, medic_id: params[:medic_id].to_i).map { |person_date|
            {title: person_date.person_id != 1 ? person_date.person.bp.to_s + ' con ' + person_date.medic.name : 'Disponible con ' + person_date.medic.name,
             start: person_date.start_time,
             color: person_date.color,
             resourceId: person_date.medic.id,
             taked: person_date.taked?
            }
          }
        end
      }

      format.html { @type = 'settimana'
      render 'layouts/calendar' }
    end
  end

  def show
    @date = PersonDate.find(params[:id])
  end

  def new
    @medics = Medic.all.map(&:name)
    @person_date = PersonDate.new
  end

  def create_medics_dates
    params.permit(:date)
    Medic.where(type: nil).all.each do |medic|
      medic.create_dates params[:date].to_date
    end
    redirect_to action: :index
  end

  def untake
    pd = PersonDate.find(params[:id])
    person = Person.find(pd.person_id)
    pd.untake
    redirect_to person_calendar_edit_path(person)
  end

  def create_kinesiologist_dates
    params.permit(:date)
    Kinesiologist.all.each do |kine|
      kine.create_dates params[:date].to_date
    end
    redirect_to action: :index
  end

  def available_dates
    params.permit(:medic_id, :date, :person_id)
    @dates = Medic.find(params[:medic_id]).available_dates params[:person_id],params[:date].to_date
    respond_to do |format|
      format.json { render json: @dates }
    end
  end

  def next_date_for_patients
    date = params[:date].blank? ? Date.current : params[:date].to_date
    @dates = Medic.find(params[:id]).next_dates_for_my_patients date
    render 'person_dates/index',layout: false
  end

  private

  def permit_params
    params.require(:person_date).permit(:date, :time, :medic_id, :person_id)
  end
end

app/views/person_dates/index.html.erb
<head>
  <title>Achs</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag href = 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %>

</head>
<style type="text/css">
@media print{
  body{ background-color:#FFFFFF; background-image:none; color:#000000 }
  #ad{ display:none;}
  #leftbar{ display:none;}
  #contentarea{ width:100%;}
}
</style>
<div class="print">
<h1>Listado de citas de hoy</h1>

<table class="table">
  <tr>
    <th>Hora</th>
    <th>Persona</th>
    <th>Medico prox cita</th>
    <th>Dia prox cita</th>
    <th>Hora prox cita</th>
    <th>Reposo?</th>
    <th>Transporte?</th>
  </tr>

  <% @dates.each do |date,ndate| %>
    <tr>
      <td><%= date.time %></td>
      <td><%= link_to "#{date.person.name} #{date.person.first_name}" , person_path(date.person)  %></td>
      <% unless ndate.blank? %>
        <td><%= link_to ndate.medic.name , medic_path(ndate.medic)  %></td>
        <td><%= ndate.date %></td>
        <td><%= ndate.time %></td>
        <% else %>
      <td></td>
        <td></td>
        <td></td>
      <% end %>
      <td><%= date.person.rest ? 'Si':'No'%></td>
      <td><%= date.person.transportation ? 'Si':'No' %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/person_dates/new.html.erb
<div class="row">
  <div class="col">
    <%= form_with scope: :person_date, url: person_dates_path, local: true do |form| %>
      <p>
        <%= form.label :fecha %><br>
        <%= form.date_field :date, value: Date.tomorrow %>
      </p>

      <p>
        <%= form.label :medico %><br>
        <%= form.collection_select :medic_id, Medic.all, :id, :name, {selected: @person.medic} %>
      </p>

      <p>
        <%= form.label :hora %><br>
        <%= form.select :time, Medic.find(@person.medic).available_dates(@person.id,Date.tomorrow).map { |date| [date.time, date.time] } %>
      </p>


      <% if params[:id] %>
        <%= form.text_field :person_id, value: params[:id], class: 'hidden' %>
      <% else %>

        <p>
          <%= form.label :persona %><br>
          <%= form.collection_select :person_id, Person.all, :id, :name %>

        </p>
      <% end %>

      <p>
        <%= form.submit :Agendar, class: 'btn btn-primary' %>
      </p>

    <% end %>
  </div>
  <div class="col-6">
    <%= render template: 'layouts/template_calendar', locals: {medic_id: '', person_dates: PersonDate.all, type: "agendaDay"} %>

  </div>
</div>

<script>
  var date = $('#person_date_date');
  var medic = $('#person_date_medic_id');
  var person = $('#person_date_person_id');

  function poblate_date() {
    $.ajax({
      url: 'available_dates',
      type: 'GET',
      data: {
        medic_id: medic.val(),
        person_id: person.val(),
        date: date.val()
      },
      success: function (data) {
        options = $('#person_date_time')[0].options;
        options.length = 0;
        data.forEach(function (option) {
          options[options.length] = new Option(option.time, option.time);
        });


      }
    });
  }

  date.change(function () {
    var date = moment($(this).val(), "YYYY-MM-DD");
    $('#calendar').fullCalendar('gotoDate', date);
    poblate_date();
  });

  medic.change(function () {
    poblate_date();
  })

</script>

app/views/person_dates/person_list.html.erb
<h1>Lista de Citas de paciente <%= @person.name %></h1>

<table class="table">
  <tr>
    <th>Dia</th>
    <th>Hora</th>
    <th>Medico</th>
    <th></th>
    <th></th>
  </tr>


  <% @buckets.each do |bucket| %>
    <tr>
      <td><%= bucket.date %></td>
      <td><%= bucket.time if bucket.is_a? PersonDate %></td>
      <td><%= link_to bucket.medic.name , medic_path(bucket.medic), class: 'btn btn-primary'  %></td>
      <td></td>
      <% if bucket.is_a? Bucket %>
      <td><%= link_to 'Liberar', untake_bucket_path(@person.id,bucket.id), class: 'btn btn-primary' %></td>
        <%end %>
        <% if bucket.is_a? PersonDate %>
        <td><%= link_to 'Liberar', untake_person_date_path(bucket), class: 'btn btn-primary' %></td>
        <%end %>

    </tr>

  <% end %>
</table>

app/views/person_dates/show.html.erb
<p>
  <strong>Hora:</strong>
  <%= @date.time %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @date.date %>
</p>
<p>
  <strong>Persona:</strong>
  <%= @date.person.name %>
</p>
<p>
  <strong>Medico:</strong>
  <%= @date.medic.name %>
</p>